### PR TITLE
Small fix in parsing.

### PR DESCRIPTION
**Pull request by bures**

### CODE REVIEW

**Comment by andris9** [comment]
Published the change as bounce-handler@7.3.2-fork.3

**Comment by bures** [comment]
Excellent. Thanks. I'll update it in Mailtrain.

BTW, we have now Mailtrain v2 beta, if you were interested. Any feedback welcome and of course big thanks for developing v1.

**Comment by andris9** [comment]
Awesome, I'll check it out!

**Comment by bures** [comment]
Looking forward. See https://github.com/Mailtrain-org/mailtrain/issues/505 for a short summary. Thanks.

**Pull request merged**
